/**
 * document.ts — Versioned save/load (JSON), §5.11. Closes PROJECT_BRIEF §6 Phase 0
 * acceptance clause 4 ("a document round-trips to JSON and back identically").
 *
 * IMPLEMENTS: PROJECT_BRIEF §5.11 ("Versioned JSON with a top-level `formatVersion`
 * integer from the first commit. Contains: format version, object list (ID, type,
 * name, slot kinds and values, stored ASTs, style), the mutation journal, and camera
 * state. Derived slot values are never serialized — they are regenerated by a full
 * evaluation pass on load." / "Loading applies objects through the mutation API and
 * then evaluates.").
 * LAYER: engine (pure). May import: engine/* only.
 *        NEVER imports: DOM, window, document, canvas, render/*.
 *        "Save via JSON download; load via file input" (§5.11) is NOT this file's job
 *        — those touch the DOM and belong to a future `render/` or `main.ts` caller.
 *        This file only converts between a `Document` and a JSON string.
 * Load-bearing per Rule 3 (§6 trigger-2 file).
 *
 * WHAT THIS IS
 *   `Document` — the bundle §5.11 describes: `formatVersion`, `nextObjectId` (D-002's
 *   counter, round-tripped as-is, never recomputed from the object list), `objects`,
 *   `journal`, and `camera` (see `CameraState`'s own comment — `render/camera.ts`
 *   is the shape's real consumer, Q-007). Like `mutate`, nothing here holds "the
 *   current document" as live state across
 *   calls (Rule 2): every function is a pure transform of the `Document` it is given.
 *
 *   `serializeDocument`/`deserializeDocument` convert between a `Document` and a
 *   plain, JSON-safe `SerializedDocument` — identical except every `derived` slot
 *   drops its `value` (§5.11's explicit exclusion). `saveDocument`/`loadDocument` wrap
 *   those with `JSON.stringify`/`JSON.parse`, which is literally what clause 4 asks
 *   for.
 *
 *   `deserializeDocument` reconstructs every object via `mutation.ts`'s
 *   `CreateObjectOperation`, in ONE batch (D-020: "Document loading MUST use a batch")
 *   — never one `mutate` call per object, which would validate and evaluate an
 *   incomplete, intermediate graph at every step, and intermediate states during a
 *   load are routinely invalid. This is also why `mutate`'s own validation (D-017/
 *   D-018 reconciliation, dangling references, D-025 illegal values) is what actually
 *   verifies a loaded document is well-formed: this file does NOT duplicate any of
 *   those checks. It does the narrower job of turning arbitrary `unknown` JSON into
 *   well-TYPED (not well-VALIDATED-against-the-graph) inputs, and trusts `mutate` for
 *   everything about whether the GRAPH is legal.
 *
 *   A zero-object document is the one case NOT routed through `mutate`: an empty batch
 *   is rejected (D-020), so "loading nothing" cannot go through the batch API — there
 *   is nothing to apply. Handled directly.
 *
 * INVARIANTS UPHELD HERE
 *   - Never throws. `loadDocument`'s `JSON.parse` is the one call here that CAN throw
 *     on malformed text — caught and returned as `{ ok: false, message }`.
 *   - `formatVersion` must EXACTLY match `FORMAT_VERSION`. There is no migration path
 *     yet — honest, not a stub: no second format version has ever been written, so
 *     there is nothing to migrate FROM.
 *   - A derived slot's load placeholder is `{ kind: "derived", value: null }`. `null`
 *     because it is a legal `Value` trivially safe under D-025; `kind: "derived"`
 *     because D-018 requires the slot PRESENT and correctly kinded before `evaluate`
 *     (inside `mutate`) overwrites it. A loader that got this wrong fails LOUDLY via
 *     D-018's existing rejection — exactly why that ruling names document loading as
 *     its motivating case.
 *   - Shape-validates only what `mutate` cannot: the top-level fields, and each
 *     object's id/name/type/slots structure, just enough to build safe
 *     `CreateObjectOperation` payloads. It does NOT validate a slot's `value`/`ast`
 *     contents, or an object's `type` against the real `ObjectType` union — a garbage
 *     `type` is treated the same honest way `getObjectSchema` treats an unrecognised
 *     one (no edges, no schema checks).
 *   - The journal's STRUCTURE is carried through unvalidated beyond `Array.isArray`:
 *     `journal: ["garbage", 42, null]` loads without complaint (verified by probe,
 *     0025-REVIEW). Nothing REPLAYS the journal, so garbage shape is inert data, and
 *     claiming a structural check that does not exist would itself be a defect. Its
 *     raw VALUES are checked, though: `rawContainsIllegalNumber` walks the
 *     parsed-but-not-yet-typed journal for any number `graph/node.ts`'s
 *     `isIllegalNumber` flags, and rejects the WHOLE document if it finds one. This is
 *     the READ-side half of D-025 — `mutate`'s payload check closes the write side,
 *     but a loaded file's journal never passes through `mutate` at all (only the
 *     object list does), so the write-side fix alone cannot reach a hand-edited or
 *     foreign file. A generic raw-value walk finds exactly the same offenders a typed
 *     one would, because every number in a well-shaped journal lives inside a
 *     `Slot.value` (`Address.objectId`/`path` are strings), for less code and no
 *     dependency on the journal's shape being trustworthy first.
 *
 * NOT DONE HERE
 *   - Reading/writing an actual file, or any DOM interaction — Phase 3 / `main.ts`.
 *   - Format migration — there is only one `FORMAT_VERSION` so far.
 *   - Deep validation of the journal's own `Operation` payloads. Nothing replays the
 *     journal (undo/redo UI is deferred, §8), so a malformed entry is inert today.
 *     Validate it for real the moment something reads it.
 *   - Allocating a fresh object id from `nextObjectId` (incrementing the counter,
 *     choosing a type's default slot values) — a FUTURE command-layer concern (§5.10,
 *     Phase 3), layered on top of `CreateObjectOperation`.
 *   - World<->screen transform math, pan, and zoom-to-cursor — `render/camera.ts`
 *     (§5.9). This file only declares and serializes the `CameraState` shape;
 *     `render/camera.ts` is the sole reader that interprets its fields as a
 *     coordinate transform, and the sole producer of a new `CameraState` outside
 *     `DEFAULT_CAMERA`.
 */
import { mutate, type MutationJournalEntry, type Operation } from "./mutation.ts";
import type { FormulaAst } from "./formula/ast.ts";
import { isIllegalNumber, type GraphObject, type ObjectType, type Slot, type Value } from "./graph/node.ts";

/** §5.11: "a top-level `formatVersion` integer from the first commit." Bump on any future format change; Phase 0 has never needed a second value. */
export const FORMAT_VERSION = 1;

/**
 * §5.11's "camera state," §5.9's own vocabulary: a world-space pan offset
 * (`x`, `y` — the world point at the screen's top-left corner) plus a zoom
 * factor. `render/camera.ts` is the shape's real owner — it defines the
 * `screen = (world - camera) * zoom` transform this shape exists to serve, and
 * is the only place a `CameraState` is ever produced besides `DEFAULT_CAMERA`
 * below. `{ x, y, zoom }` needed no widening to support it (Q-007, resolved by
 * `render/camera.ts`): the transform needs no viewport size, so this shape is
 * already sufficient. This file's own job stays narrow — declare the shape and
 * serialize/deserialize it (D-027's numeric-legality guard included) — never a
 * second reader that interprets what the fields mean.
 */
export interface CameraState {
  readonly x: number;
  readonly y: number;
  readonly zoom: number;
}

const DEFAULT_CAMERA: CameraState = { x: 0, y: 0, zoom: 1 };

/**
 * The complete document bundle §5.11 describes. Plain, readonly, fully
 * serializable data (Rule 2) — no closures, no live state, matching every
 * other data shape in this codebase.
 */
export interface Document {
  readonly formatVersion: number;
  /** D-002: the counter object ids are minted from. Round-tripped as-is; NEVER recomputed from `objects`. */
  readonly nextObjectId: number;
  readonly objects: readonly GraphObject[];
  readonly journal: readonly MutationJournalEntry[];
  readonly camera: CameraState;
}

/** A fresh, empty document — `nextObjectId` starts at 1 (D-002: `obj_1` is the first id any future creation mints). */
export function createEmptyDocument(): Document {
  return { formatVersion: FORMAT_VERSION, nextObjectId: 1, objects: [], journal: [], camera: DEFAULT_CAMERA };
}

// ---------------------------------------------------------------------------
// Serialized shapes — identical to the in-memory ones, except a derived slot
// never carries `value` (§5.11's explicit exclusion).
// ---------------------------------------------------------------------------

/** A `derived` slot serializes as its kind alone — no `value` (§5.11). `literal`/`formula` slots serialize unchanged; every member of `Value` they can hold is already plain JSON-safe data (D-025 is what makes this true for `number` too). */
export type SerializedSlot = { readonly kind: "literal"; readonly value: Value } | { readonly kind: "formula"; readonly ast: FormulaAst; readonly value: Value } | { readonly kind: "derived" };

export interface SerializedGraphObject {
  readonly id: string;
  readonly name: string;
  readonly type: ObjectType;
  readonly slots: Readonly<Record<string, SerializedSlot>>;
}

export interface SerializedDocument {
  readonly formatVersion: number;
  readonly nextObjectId: number;
  readonly objects: readonly SerializedGraphObject[];
  readonly journal: readonly MutationJournalEntry[];
  readonly camera: CameraState;
}

/** §5.11: drops every `derived` slot's `value`. Never throws — `document` is already well-typed, in-memory data. */
export function serializeDocument(document: Document): SerializedDocument {
  return {
    formatVersion: document.formatVersion,
    nextObjectId: document.nextObjectId,
    objects: document.objects.map(serializeObject),
    journal: document.journal,
    camera: document.camera,
  };
}

function serializeObject(object: GraphObject): SerializedGraphObject {
  const slots: Record<string, SerializedSlot> = {};
  for (const key of Object.keys(object.slots)) {
    const slot = object.slots[key];
    if (slot === undefined) {
      continue; // noUncheckedIndexedAccess artifact only — key came from Object.keys of this same record.
    }
    slots[key] = slot.kind === "derived" ? { kind: "derived" } : slot;
  }
  return { id: object.id, name: object.name, type: object.type, slots };
}

/** `saveDocument`'s/`deserializeDocument`'s shared ok/fail shape, matching every other typed result in this codebase (`MutationResult`, `IntegrityCheckResult`). */
export type DocumentLoadResult = { readonly ok: true; readonly document: Document } | { readonly ok: false; readonly message: string };

/**
 * `JSON.stringify(serializeDocument(document))` — the literal "round-trips to
 * JSON" half of clause 4. Never throws.
 *
 * An earlier wording of this comment claimed `JSON.stringify` "cannot
 * silently lose information here" — WRONG when it was written (corrected at
 * 0025-REVIEW-phase0, whose finding 1 is exactly that claim's counterexample:
 * a journal payload holding `Infinity` stringified to `null`). As of cycle
 * 0026 the claim is TRUE for the object list and the journal, and for a
 * load-bearing reason rather than by accident: `mutate` (`mutation.ts`) now
 * rejects any operation whose payload is illegal (D-025/Q-008) BEFORE it can
 * enter either one. It is NOT true of `camera` (corrected at 0027-REVIEW,
 * which found `1e999` and `-0` still round-tripping wrongly there): camera
 * state never passes through `mutate`, and this function has no failure
 * channel with which to reject one — it returns a `string`. Today nothing in
 * the tree writes a camera except `DEFAULT_CAMERA`, so no document this
 * software produces holds an illegal one; `deserializeDocument` rejects such a
 * file on load, so the failure is loud rather than silent. **D-027 binds
 * whoever first writes real camera state (Phase 3) to keep it that way** —
 * a NaN zoom saves as `null` and makes the document unloadable. `deserializeDocument`'s own journal check (see its
 * doc comment) closes the other direction, for a `Document` this software did
 * NOT produce (a hand-edited or foreign file): such a file is rejected
 * outright rather than silently accepted-then-corrupted. Together, any
 * `Document` this function is ever called on is one `loadDocument` can
 * reconstruct byte-for-byte — see `document.test.ts`'s
 * `expect(saveDocument(loaded)).toBe(json)` round-trip.
 */
export function saveDocument(document: Document): string {
  return JSON.stringify(serializeDocument(document));
}

/**
 * The other half of "round-trips to JSON and back": parses `json`, then
 * defers to `deserializeDocument`. `JSON.parse` is the one place in this file
 * that can throw (malformed JSON text) — caught here so this function upholds
 * the same never-throws discipline as everything else.
 */
export function loadDocument(json: string): DocumentLoadResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return { ok: false, message: `document is not valid JSON: ${reason}` };
  }
  return deserializeDocument(parsed);
}

/** Narrows `value` to a non-null, non-array plain object — the shape every structural check below needs before indexing into it. */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * D-025/Q-008 on the READ side (cycle 0026, closing 0025-REVIEW-phase0
 * finding 1's other half — see the file header). Walks raw, not-yet-typed
 * JSON data — the parsed but unvalidated `journal` field — looking for ANY
 * number `graph/node.ts`'s `isIllegalNumber` flags, anywhere within it.
 *
 * Deliberately generic rather than shaped around `Operation`'s variants: it
 * does not need to know whether a given number is a `setSlot`'s
 * `slot.value.x` or a `createObject`'s `object.slots["out.result"].value` —
 * only that a well-shaped journal's only numbers live inside a `Slot.value`
 * (`Address.objectId` and `path` are always strings), so finding one
 * anywhere in the structure is exactly as thorough as a fully-typed walk
 * would be, without first needing to trust that the structure IS well-shaped
 * (this file's own stance is that journal STRUCTURE stays unvalidated — see
 * the header — so a value-legality check that required well-formed structure
 * first would be the wrong tool).
 *
 * Never throws — `Object.values` on a non-null object and a plain recursive
 * walk cannot throw for any JSON-derived `unknown`.
 */
function rawContainsIllegalNumber(raw: unknown): boolean {
  if (typeof raw === "number") {
    return isIllegalNumber(raw);
  }
  if (Array.isArray(raw)) {
    return raw.some(rawContainsIllegalNumber);
  }
  if (typeof raw === "object" && raw !== null) {
    return Object.values(raw).some(rawContainsIllegalNumber);
  }
  return false; // string, boolean, null, undefined
}

/**
 * Validates and reconstructs a `Document` from arbitrary `unknown` JSON data
 * — see the file header's INVARIANTS UPHELD HERE for exactly what this
 * function checks itself versus what it hands off to `mutate`'s own
 * validation. Never throws.
 */
export function deserializeDocument(raw: unknown): DocumentLoadResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `a document must be a JSON object, not ${describeTypeof(raw)}` };
  }
  if (raw.formatVersion !== FORMAT_VERSION) {
    return {
      ok: false,
      message: `unsupported document formatVersion ${JSON.stringify(raw.formatVersion)} — this build only reads formatVersion ${FORMAT_VERSION}`,
    };
  }
  // D-027 (0027-REVIEW): `Number.isInteger` already excludes NaN and both
  // infinities, but NOT `-0`, which JSON writes back as `0` — the same
  // round-trip defect as every other illegal number, on the counter instead of
  // a slot value. Value legality is a property of the whole document.
  if (
    typeof raw.nextObjectId !== "number" ||
    !Number.isInteger(raw.nextObjectId) ||
    raw.nextObjectId < 0 ||
    isIllegalNumber(raw.nextObjectId)
  ) {
    return { ok: false, message: "nextObjectId must be a non-negative integer, and not -0 (D-002/D-027)" };
  }
  if (!Array.isArray(raw.objects)) {
    return { ok: false, message: "objects must be an array" };
  }
  if (!Array.isArray(raw.journal)) {
    return { ok: false, message: "journal must be an array" };
  }
  if (rawContainsIllegalNumber(raw.journal)) {
    // D-025/Q-008, read side (cycle 0026): a loaded journal never passes
    // through `mutate`, so its own write-side payload check never sees this
    // file — see rawContainsIllegalNumber's own doc comment and the file
    // header. The document is rejected outright rather than silently loaded
    // with a corrupted history.
    return { ok: false, message: "journal contains an illegal number (non-finite, or -0), which is not legal document state (D-025/Q-008)" };
  }
  const cameraResult = reconstructCamera(raw.camera);
  if (!cameraResult.ok) {
    return cameraResult;
  }

  const reconstructedObjects: GraphObject[] = [];
  for (let index = 0; index < raw.objects.length; index += 1) {
    const objectResult = reconstructObject(raw.objects[index], index);
    if (!objectResult.ok) {
      return objectResult;
    }
    reconstructedObjects.push(objectResult.object);
  }

  const nextObjectId = raw.nextObjectId;
  // The journal is carried through as historical data, unvalidated beyond
  // "an array" (see file header's NOT DONE HERE) — nothing replays it yet.
  const journal = raw.journal as readonly MutationJournalEntry[];

  if (reconstructedObjects.length === 0) {
    // D-020/0021-REVIEW: an empty batch is rejected by `mutate` outright — a
    // zero-object document must not be routed through it at all.
    return { ok: true, document: { formatVersion: FORMAT_VERSION, nextObjectId, objects: [], journal, camera: cameraResult.camera } };
  }

  // §5.11: "Loading applies objects through the mutation API [in a batch,
  // D-020] and then evaluates" — `mutate`'s own pipeline already evaluates
  // (deriveValidateAndEvaluate's step 7) as the last step of the SAME call,
  // so there is no separate "evaluate" call needed here.
  const operations: readonly Operation[] = reconstructedObjects.map((object) => ({ kind: "createObject", object }));
  const result = mutate([], operations, []);
  if (!result.ok) {
    return { ok: false, message: result.message };
  }

  return {
    ok: true,
    document: { formatVersion: FORMAT_VERSION, nextObjectId, objects: result.objects, journal, camera: cameraResult.camera },
  };
}

type CameraReconstructionResult = { readonly ok: true; readonly camera: CameraState } | { readonly ok: false; readonly message: string };

function reconstructCamera(raw: unknown): CameraReconstructionResult {
  if (!isPlainObject(raw) || typeof raw.x !== "number" || typeof raw.y !== "number" || typeof raw.zoom !== "number") {
    return { ok: false, message: "camera must be an object with numeric x, y, and zoom (see CameraState's doc comment)" };
  }
  // D-027 (0027-REVIEW): the camera is document state like anything else, and
  // its three numbers go through the same JSON — a file holding `1e999` parses
  // to `Infinity` and saves back as `null`; `-0` saves as `0`. Cycle 0026
  // closed exactly this for the object list and the journal; the camera is the
  // third numeric surface of the same `Document`, and the rule belongs to the
  // document, not to the slot. Read side only: `saveDocument` has no failure
  // channel to reject an in-memory camera (see its own doc comment), which is
  // why D-027 binds whoever WRITES camera state in Phase 3.
  if (isIllegalNumber(raw.x) || isIllegalNumber(raw.y) || isIllegalNumber(raw.zoom)) {
    return {
      ok: false,
      message: "camera holds an illegal number (non-finite, or -0), which is not legal document state (D-025/Q-008/D-027)",
    };
  }
  return { ok: true, camera: { x: raw.x, y: raw.y, zoom: raw.zoom } };
}

type ObjectReconstructionResult = { readonly ok: true; readonly object: GraphObject } | { readonly ok: false; readonly message: string };

/**
 * Structural validation ONLY — id/name/type present and correctly typed, and
 * `slots` an object whose every entry `reconstructSlot` can make sense of.
 * Deliberately does NOT check `type` against the real `ObjectType` union
 * (the same honest-`undefined` stance `getObjectSchema` already takes for an
 * unrecognised type — no edges derived, no schema checks applied to it) or
 * validate a slot's actual `value`/`ast` CONTENT — `mutate`'s own
 * `validateIntegrity` is what catches a dangling reference, a schema/kind
 * mismatch, or a non-finite number, over the FULLY reconstructed graph.
 */
function reconstructObject(raw: unknown, index: number): ObjectReconstructionResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `objects[${index}] must be an object` };
  }
  const { id, name, type, slots: rawSlots } = raw;
  if (typeof id !== "string" || typeof name !== "string" || typeof type !== "string") {
    return { ok: false, message: `objects[${index}] must have a string id, name, and type` };
  }
  if (!isPlainObject(rawSlots)) {
    return { ok: false, message: `${name}.slots must be an object` };
  }

  const slots: Record<string, Slot> = {};
  for (const key of Object.keys(rawSlots)) {
    const slotResult = reconstructSlot(rawSlots[key], name, key);
    if (!slotResult.ok) {
      return slotResult;
    }
    slots[key] = slotResult.slot;
  }

  // The cast is deliberate, not an oversight — see this function's own doc
  // comment: an unrecognised `type` string is treated the same honest way
  // `getObjectSchema` already treats one, not rejected here.
  return { ok: true, object: { id, name, type: type as ObjectType, slots } };
}

type SlotReconstructionResult = { readonly ok: true; readonly slot: Slot } | { readonly ok: false; readonly message: string };

/**
 * §5.11: a `derived` slot's `value` is NEVER serialized, so it is always
 * reconstructed as the `{ kind: "derived", value: null }` placeholder
 * (D-018/D-025 — see file header) regardless of anything a malformed or
 * hand-edited file might additionally carry under that key. `literal`/
 * `formula` slots are trusted for their `value`/`ast` CONTENT (see
 * `reconstructObject`'s own doc comment for why) — only their `kind` and the
 * presence of the field they need are checked here.
 */
function reconstructSlot(raw: unknown, objectName: string, key: string): SlotReconstructionResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `${objectName}.${key} must be an object` };
  }
  if (raw.kind === "literal") {
    if (!("value" in raw)) {
      return { ok: false, message: `${objectName}.${key} (literal) is missing its value` };
    }
    return { ok: true, slot: { kind: "literal", value: raw.value as Value } };
  }
  if (raw.kind === "formula") {
    if (!("ast" in raw)) {
      return { ok: false, message: `${objectName}.${key} (formula) is missing its ast` };
    }
    return { ok: true, slot: { kind: "formula", ast: raw.ast as FormulaAst, value: "value" in raw ? (raw.value as Value) : null } };
  }
  if (raw.kind === "derived") {
    return { ok: true, slot: { kind: "derived", value: null } };
  }
  return { ok: false, message: `${objectName}.${key} has an unrecognised slot kind ${JSON.stringify(raw.kind)}` };
}

/** A short, human-readable description of `typeof value`, for a top-level shape-error message — never itself throws. */
function describeTypeof(value: unknown): string {
  if (value === null) {
    return "null";
  }
  if (Array.isArray(value)) {
    return "an array";
  }
  return `a ${typeof value}`;
}
