/**
 * document.ts — Versioned save/load (JSON), §5.11. THE last file Phase 0's build
 * order names (`address.ts`, `graph/*`, `primitives/schema.ts`, `mutation.ts`,
 * `document.ts`) and closes PROJECT_BRIEF §6 Phase 0 acceptance clause 4 ("a
 * document round-trips to JSON and back identically").
 *
 * IMPLEMENTS: PROJECT_BRIEF §5.11 ("Versioned JSON with a top-level
 * `formatVersion` integer from the first commit. Contains: format version,
 * object list (ID, type, name, slot kinds and values, stored ASTs, style), the
 * mutation journal, and camera state. Derived slot values are never
 * serialized — they are regenerated by a full evaluation pass on load." /
 * "Loading applies objects through the mutation API and then evaluates.").
 * Load-bearing per Rule 3 (§6 trigger-2 file: new subsystem) and PROCESS_BRIEF
 * §6 trigger-3 (new engine file) — cycle 0024 (first version of this file)
 * was a MANDATORY review point regardless of the batching cap (§6.1 trigger
 * 2). 0025-REVIEW-phase0 (REVISE) found clause 4 not genuinely closed —
 * D-025 was never enforced over the mutation journal (finding 1) — and two
 * smaller defects (findings 2-3, in `mutation.ts`). Cycle 0026 closes finding
 * 1's read-side half here (`rawContainsIllegalNumber`, see below and the
 * INVARIANTS UPHELD HERE section) and, together with `mutation.ts`'s cycle
 * 0026 write-side fix, re-closes clause 4 for real.
 * LAYER: engine (pure). May import: engine/* only.
 *        NEVER imports: DOM, window, document, canvas, render/*.
 *        "Save via JSON download; load via file input" (§5.11) is NOT this
 *        file's job — those touch the DOM and belong to a future `render/`
 *        or `main.ts` caller. This file only converts between a `Document`
 *        and a JSON string; nothing here reads a file or writes to disk.
 *
 * WHAT THIS IS
 *   `Document` — the complete bundle §5.11 describes: `formatVersion`,
 *   `nextObjectId` (D-002's counter, round-tripped as-is, never recomputed
 *   from the object list), the full `objects` list, the mutation `journal`,
 *   and `camera` (see `CameraState`'s own doc comment — PROVISIONAL(Q-007)).
 *   Like `mutation.ts`'s `mutate`, this file does NOT hold "the current
 *   document" as live state across calls (Rule 2: no closures/stored state)
 *   — every function here is a pure transform of the `Document` it is given.
 *
 *   `serializeDocument` / `deserializeDocument` convert between a `Document`
 *   and a `SerializedDocument` — a plain, JSON-safe shape identical to
 *   `Document` except every `derived`-kind slot drops its `value` field
 *   (§5.11's explicit exclusion — DerivedSlot.value is regenerated by
 *   evaluation, never stored). `saveDocument` / `loadDocument` wrap those with
 *   `JSON.stringify`/`JSON.parse`, which is the literal "round-trips to JSON"
 *   clause 4 asks for.
 *
 *   `deserializeDocument` reconstructs every object via `mutation.ts`'s
 *   `CreateObjectOperation`, in ONE batch (D-020: "Document loading MUST use
 *   a batch") — never one `mutate` call per object, which would validate and
 *   evaluate an incomplete, intermediate graph at every step (mutation.ts's
 *   own D-020 rationale: "intermediate states during a load are routinely
 *   invalid"). This is also why `mutate`'s own validation (schema
 *   reconciliation D-017/D-018, dangling references, D-025 non-finite
 *   values) is what actually verifies a loaded document is well-formed — this
 *   file does NOT duplicate any of those checks; it only does the narrower
 *   job of turning arbitrary `unknown` JSON into well-TYPED (not
 *   well-VALIDATED-against-the-graph) inputs `mutate` can accept, and trusts
 *   `mutate` for everything about whether the GRAPH itself is legal.
 *
 *   A zero-object document is the one case NOT routed through `mutate` at
 *   all (D-020/0021-REVIEW's own carried note: an empty batch is rejected,
 *   so "loading nothing" cannot go through the batch API — there is nothing
 *   to apply). Handled directly: the empty `objects: []` is returned as-is.
 *
 * INVARIANTS UPHELD HERE
 *   - Never throws. `loadDocument`'s `JSON.parse` is the one call in this
 *     file that CAN throw on malformed JSON text — caught and turned into
 *     `{ ok: false, message }`, matching every other function in this
 *     codebase's discipline.
 *   - `formatVersion` is checked for an EXACT match against `FORMAT_VERSION`
 *     on load; there is no migration path yet (honest, not a stub — Phase 0
 *     has never written a second format version, so there is nothing to
 *     migrate FROM).
 *   - A derived slot's placeholder on load is `{ kind: "derived", value:
 *     null }` — `null` because it is a legal `Value` member trivially safe
 *     under D-025 (not a number, so `hasNonFiniteNumber` never flags it), and
 *     `kind: "derived"` because D-018 requires the slot to be PRESENT and
 *     correctly kinded before `evaluate` (invoked inside `mutate`) overwrites
 *     the placeholder with the real recomputed value. A loader that got this
 *     wrong (wrong kind, or omitted the slot) fails LOUDLY via D-018's
 *     existing rejection — exactly why that ruling names document loading as
 *     its own motivating case.
 *   - Shape-validates only what `mutate` cannot: the top-level `Document`
 *     fields (`formatVersion`, `nextObjectId`, `camera`, and that `objects`/
 *     `journal` are arrays) and each object's own id/name/type/slots
 *     structure, just enough to safely build `CreateObjectOperation`
 *     payloads. Does NOT validate a slot's `value`/`ast` contents, or an
 *     object's `type` against the real `ObjectType` union — a garbage `type`
 *     string is treated the same honest way `getObjectSchema` already treats
 *     an unrecognised one (no edges derived, no schema checks applied), and
 *     anything wrong with a slot's actual content is `mutate`'s job to catch.
 *   - The journal's STRUCTURE is carried through unvalidated beyond
 *     `Array.isArray` — `journal: ["garbage", 42, null]` loads without a
 *     structural complaint, verified by probe at 0025-REVIEW-phase0. That
 *     stays true here: nothing REPLAYS the journal yet (see NOT DONE HERE),
 *     so garbage shape is inert data, and claiming a structural check that
 *     does not exist would be the same defect 0025-REVIEW-phase0 corrected
 *     once already. What changed at cycle 0026: the journal's raw VALUES are
 *     checked — `rawContainsIllegalNumber` below walks the parsed-but-not-yet-
 *     typed journal looking for any `Value`-shaped number `graph/node.ts`'s
 *     `isIllegalNumber` flags, and `deserializeDocument` rejects the WHOLE
 *     document if it finds one. This is 0025-REVIEW-phase0 finding 1's other
 *     half: `mutate`'s own new payload check (`mutation.ts`, cycle 0026)
 *     closes the WRITE side (nothing this software produces can ever put an
 *     illegal number in a journal again), but a loaded file's journal never
 *     passes THROUGH `mutate` at all — only the object list does, via
 *     `CreateObjectOperation` — so the write-side fix alone cannot reach a
 *     hand-edited or otherwise foreign file. This check is what closes THAT
 *     gap, directly, rather than reconstructing typed `Operation`s just to
 *     re-run `mutate`'s own check on them (Rule 5: the journal's only illegal
 *     content a rejection needs to notice is a number, and every number
 *     anywhere in a well-shaped journal already lives inside a `Slot.value`
 *     — `Address.objectId`/`path` are strings, never numbers — so a generic
 *     raw-value walk finds exactly the same offenders a typed one would,
 *     for less code and no dependency on the journal's shape being trustworthy
 *     first).
 *
 * NOT DONE HERE
 *   - Actually reading/writing a file, or any DOM interaction (`<input
 *     type=file>`, a download link) — Phase 3/`main.ts`'s job, per this
 *     file's own LAYER note.
 *   - Format migration — there is only ever one `FORMAT_VERSION` so far.
 *   - Deep validation of the mutation journal's own `Operation` payloads
 *     (e.g. that a `setSlot`'s `address` is shaped correctly) — nothing
 *     REPLAYS the journal yet (undo/redo UI is itself deferred, PROJECT_BRIEF
 *     §8), so a malformed journal entry is inert data today. Validate it for
 *     real the moment something reads it.
 *   - Allocating a fresh object id from `nextObjectId` (incrementing the
 *     counter, choosing a type's default slot values) — that is a FUTURE
 *     command-layer concern (§5.10, Phase 3: a user-facing "add a new
 *     circle"), layered on top of `CreateObjectOperation`, not this file's.
 *   - `CameraState`'s real shape — PROVISIONAL(Q-007): `render/camera.ts`
 *     does not exist yet (Phase 3). This file's `{ x, y, zoom }` is a
 *     minimal, reversible placeholder Phase 3 may widen.
 */
import { mutate, type MutationJournalEntry, type Operation } from "./mutation.ts";
import type { FormulaAst } from "./formula/ast.ts";
import { isIllegalNumber, type GraphObject, type ObjectType, type Slot, type Value } from "./graph/node.ts";

/** §5.11: "a top-level `formatVersion` integer from the first commit." Bump on any future format change; Phase 0 has never needed a second value. */
export const FORMAT_VERSION = 1;

/**
 * PROVISIONAL(Q-007): the minimal, reversible placeholder camera state Phase
 * 0 needs to round-trip SOMETHING today — `render/camera.ts` (Phase 3, §5.9:
 * "world → screen and screen → world," pan/zoom) does not exist yet. A plain
 * world-space pan offset plus a zoom factor is the direct reading of §5.9's
 * own vocabulary. Phase 3 may widen this; nothing outside `document.ts` reads
 * it yet, so doing so costs nothing today.
 */
export interface CameraState {
  readonly x: number;
  readonly y: number;
  readonly zoom: number;
}

const DEFAULT_CAMERA: CameraState = { x: 0, y: 0, zoom: 1 };

/**
 * The complete document bundle §5.11 describes. Plain, readonly, fully
 * serializable data (Rule 2) — no closures, no live state, matching every
 * other data shape in this codebase.
 */
export interface Document {
  readonly formatVersion: number;
  /** D-002: the counter object ids are minted from. Round-tripped as-is; NEVER recomputed from `objects`. */
  readonly nextObjectId: number;
  readonly objects: readonly GraphObject[];
  readonly journal: readonly MutationJournalEntry[];
  readonly camera: CameraState;
}

/** A fresh, empty document — `nextObjectId` starts at 1 (D-002: `obj_1` is the first id any future creation mints). */
export function createEmptyDocument(): Document {
  return { formatVersion: FORMAT_VERSION, nextObjectId: 1, objects: [], journal: [], camera: DEFAULT_CAMERA };
}

// ---------------------------------------------------------------------------
// Serialized shapes — identical to the in-memory ones, except a derived slot
// never carries `value` (§5.11's explicit exclusion).
// ---------------------------------------------------------------------------

/** A `derived` slot serializes as its kind alone — no `value` (§5.11). `literal`/`formula` slots serialize unchanged; every member of `Value` they can hold is already plain JSON-safe data (D-025 is what makes this true for `number` too — see this cycle's log entry). */
export type SerializedSlot = { readonly kind: "literal"; readonly value: Value } | { readonly kind: "formula"; readonly ast: FormulaAst; readonly value: Value } | { readonly kind: "derived" };

export interface SerializedGraphObject {
  readonly id: string;
  readonly name: string;
  readonly type: ObjectType;
  readonly slots: Readonly<Record<string, SerializedSlot>>;
}

export interface SerializedDocument {
  readonly formatVersion: number;
  readonly nextObjectId: number;
  readonly objects: readonly SerializedGraphObject[];
  readonly journal: readonly MutationJournalEntry[];
  readonly camera: CameraState;
}

/** §5.11: drops every `derived` slot's `value`. Never throws — `document` is already well-typed, in-memory data. */
export function serializeDocument(document: Document): SerializedDocument {
  return {
    formatVersion: document.formatVersion,
    nextObjectId: document.nextObjectId,
    objects: document.objects.map(serializeObject),
    journal: document.journal,
    camera: document.camera,
  };
}

function serializeObject(object: GraphObject): SerializedGraphObject {
  const slots: Record<string, SerializedSlot> = {};
  for (const key of Object.keys(object.slots)) {
    const slot = object.slots[key];
    if (slot === undefined) {
      continue; // noUncheckedIndexedAccess artifact only — key came from Object.keys of this same record.
    }
    slots[key] = slot.kind === "derived" ? { kind: "derived" } : slot;
  }
  return { id: object.id, name: object.name, type: object.type, slots };
}

/** `saveDocument`'s/`deserializeDocument`'s shared ok/fail shape, matching every other typed result in this codebase (`MutationResult`, `IntegrityCheckResult`). */
export type DocumentLoadResult = { readonly ok: true; readonly document: Document } | { readonly ok: false; readonly message: string };

/**
 * `JSON.stringify(serializeDocument(document))` — the literal "round-trips to
 * JSON" half of clause 4. Never throws.
 *
 * An earlier wording of this comment claimed `JSON.stringify` "cannot
 * silently lose information here" — WRONG when it was written (corrected at
 * 0025-REVIEW-phase0, whose finding 1 is exactly that claim's counterexample:
 * a journal payload holding `Infinity` stringified to `null`). As of cycle
 * 0026 the claim is TRUE again, but for a different, load-bearing reason, not
 * by accident: `mutate` (`mutation.ts`) now rejects any operation whose
 * payload is illegal (D-025/Q-008) BEFORE it can ever enter the journal, so
 * no `Document` this software produces can hold an illegal number anywhere —
 * object list or journal. `deserializeDocument`'s own journal check (see its
 * doc comment) closes the other direction, for a `Document` this software did
 * NOT produce (a hand-edited or foreign file): such a file is rejected
 * outright rather than silently accepted-then-corrupted. Together, any
 * `Document` this function is ever called on is one `loadDocument` can
 * reconstruct byte-for-byte — see `document.test.ts`'s
 * `expect(saveDocument(loaded)).toBe(json)` round-trip.
 */
export function saveDocument(document: Document): string {
  return JSON.stringify(serializeDocument(document));
}

/**
 * The other half of "round-trips to JSON and back": parses `json`, then
 * defers to `deserializeDocument`. `JSON.parse` is the one place in this file
 * that can throw (malformed JSON text) — caught here so this function upholds
 * the same never-throws discipline as everything else.
 */
export function loadDocument(json: string): DocumentLoadResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(json);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return { ok: false, message: `document is not valid JSON: ${reason}` };
  }
  return deserializeDocument(parsed);
}

/** Narrows `value` to a non-null, non-array plain object — the shape every structural check below needs before indexing into it. */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * D-025/Q-008 on the READ side (cycle 0026, closing 0025-REVIEW-phase0
 * finding 1's other half — see the file header). Walks raw, not-yet-typed
 * JSON data — the parsed but unvalidated `journal` field — looking for ANY
 * number `graph/node.ts`'s `isIllegalNumber` flags, anywhere within it.
 *
 * Deliberately generic rather than shaped around `Operation`'s variants: it
 * does not need to know whether a given number is a `setSlot`'s
 * `slot.value.x` or a `createObject`'s `object.slots["out.result"].value` —
 * only that a well-shaped journal's only numbers live inside a `Slot.value`
 * (`Address.objectId` and `path` are always strings), so finding one
 * anywhere in the structure is exactly as thorough as a fully-typed walk
 * would be, without first needing to trust that the structure IS well-shaped
 * (this file's own stance is that journal STRUCTURE stays unvalidated — see
 * the header — so a value-legality check that required well-formed structure
 * first would be the wrong tool).
 *
 * Never throws — `Object.values` on a non-null object and a plain recursive
 * walk cannot throw for any JSON-derived `unknown`.
 */
function rawContainsIllegalNumber(raw: unknown): boolean {
  if (typeof raw === "number") {
    return isIllegalNumber(raw);
  }
  if (Array.isArray(raw)) {
    return raw.some(rawContainsIllegalNumber);
  }
  if (typeof raw === "object" && raw !== null) {
    return Object.values(raw).some(rawContainsIllegalNumber);
  }
  return false; // string, boolean, null, undefined
}

/**
 * Validates and reconstructs a `Document` from arbitrary `unknown` JSON data
 * — see the file header's INVARIANTS UPHELD HERE for exactly what this
 * function checks itself versus what it hands off to `mutate`'s own
 * validation. Never throws.
 */
export function deserializeDocument(raw: unknown): DocumentLoadResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `a document must be a JSON object, not ${describeTypeof(raw)}` };
  }
  if (raw.formatVersion !== FORMAT_VERSION) {
    return {
      ok: false,
      message: `unsupported document formatVersion ${JSON.stringify(raw.formatVersion)} — this build only reads formatVersion ${FORMAT_VERSION}`,
    };
  }
  if (typeof raw.nextObjectId !== "number" || !Number.isInteger(raw.nextObjectId) || raw.nextObjectId < 0) {
    return { ok: false, message: "nextObjectId must be a non-negative integer (D-002)" };
  }
  if (!Array.isArray(raw.objects)) {
    return { ok: false, message: "objects must be an array" };
  }
  if (!Array.isArray(raw.journal)) {
    return { ok: false, message: "journal must be an array" };
  }
  if (rawContainsIllegalNumber(raw.journal)) {
    // D-025/Q-008, read side (cycle 0026): a loaded journal never passes
    // through `mutate`, so its own write-side payload check never sees this
    // file — see rawContainsIllegalNumber's own doc comment and the file
    // header. The document is rejected outright rather than silently loaded
    // with a corrupted history.
    return { ok: false, message: "journal contains an illegal number (non-finite, or -0), which is not legal document state (D-025/Q-008)" };
  }
  const cameraResult = reconstructCamera(raw.camera);
  if (!cameraResult.ok) {
    return cameraResult;
  }

  const reconstructedObjects: GraphObject[] = [];
  for (let index = 0; index < raw.objects.length; index += 1) {
    const objectResult = reconstructObject(raw.objects[index], index);
    if (!objectResult.ok) {
      return objectResult;
    }
    reconstructedObjects.push(objectResult.object);
  }

  const nextObjectId = raw.nextObjectId;
  // The journal is carried through as historical data, unvalidated beyond
  // "an array" (see file header's NOT DONE HERE) — nothing replays it yet.
  const journal = raw.journal as readonly MutationJournalEntry[];

  if (reconstructedObjects.length === 0) {
    // D-020/0021-REVIEW: an empty batch is rejected by `mutate` outright — a
    // zero-object document must not be routed through it at all.
    return { ok: true, document: { formatVersion: FORMAT_VERSION, nextObjectId, objects: [], journal, camera: cameraResult.camera } };
  }

  // §5.11: "Loading applies objects through the mutation API [in a batch,
  // D-020] and then evaluates" — `mutate`'s own pipeline already evaluates
  // (deriveValidateAndEvaluate's step 7) as the last step of the SAME call,
  // so there is no separate "evaluate" call needed here.
  const operations: readonly Operation[] = reconstructedObjects.map((object) => ({ kind: "createObject", object }));
  const result = mutate([], operations, []);
  if (!result.ok) {
    return { ok: false, message: result.message };
  }

  return {
    ok: true,
    document: { formatVersion: FORMAT_VERSION, nextObjectId, objects: result.objects, journal, camera: cameraResult.camera },
  };
}

type CameraReconstructionResult = { readonly ok: true; readonly camera: CameraState } | { readonly ok: false; readonly message: string };

function reconstructCamera(raw: unknown): CameraReconstructionResult {
  if (!isPlainObject(raw) || typeof raw.x !== "number" || typeof raw.y !== "number" || typeof raw.zoom !== "number") {
    return { ok: false, message: "camera must be an object with numeric x, y, and zoom (PROVISIONAL(Q-007))" };
  }
  return { ok: true, camera: { x: raw.x, y: raw.y, zoom: raw.zoom } };
}

type ObjectReconstructionResult = { readonly ok: true; readonly object: GraphObject } | { readonly ok: false; readonly message: string };

/**
 * Structural validation ONLY — id/name/type present and correctly typed, and
 * `slots` an object whose every entry `reconstructSlot` can make sense of.
 * Deliberately does NOT check `type` against the real `ObjectType` union
 * (the same honest-`undefined` stance `getObjectSchema` already takes for an
 * unrecognised type — no edges derived, no schema checks applied to it) or
 * validate a slot's actual `value`/`ast` CONTENT — `mutate`'s own
 * `validateIntegrity` is what catches a dangling reference, a schema/kind
 * mismatch, or a non-finite number, over the FULLY reconstructed graph.
 */
function reconstructObject(raw: unknown, index: number): ObjectReconstructionResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `objects[${index}] must be an object` };
  }
  const { id, name, type, slots: rawSlots } = raw;
  if (typeof id !== "string" || typeof name !== "string" || typeof type !== "string") {
    return { ok: false, message: `objects[${index}] must have a string id, name, and type` };
  }
  if (!isPlainObject(rawSlots)) {
    return { ok: false, message: `${name}.slots must be an object` };
  }

  const slots: Record<string, Slot> = {};
  for (const key of Object.keys(rawSlots)) {
    const slotResult = reconstructSlot(rawSlots[key], name, key);
    if (!slotResult.ok) {
      return slotResult;
    }
    slots[key] = slotResult.slot;
  }

  // The cast is deliberate, not an oversight — see this function's own doc
  // comment: an unrecognised `type` string is treated the same honest way
  // `getObjectSchema` already treats one, not rejected here.
  return { ok: true, object: { id, name, type: type as ObjectType, slots } };
}

type SlotReconstructionResult = { readonly ok: true; readonly slot: Slot } | { readonly ok: false; readonly message: string };

/**
 * §5.11: a `derived` slot's `value` is NEVER serialized, so it is always
 * reconstructed as the `{ kind: "derived", value: null }` placeholder
 * (D-018/D-025 — see file header) regardless of anything a malformed or
 * hand-edited file might additionally carry under that key. `literal`/
 * `formula` slots are trusted for their `value`/`ast` CONTENT (see
 * `reconstructObject`'s own doc comment for why) — only their `kind` and the
 * presence of the field they need are checked here.
 */
function reconstructSlot(raw: unknown, objectName: string, key: string): SlotReconstructionResult {
  if (!isPlainObject(raw)) {
    return { ok: false, message: `${objectName}.${key} must be an object` };
  }
  if (raw.kind === "literal") {
    if (!("value" in raw)) {
      return { ok: false, message: `${objectName}.${key} (literal) is missing its value` };
    }
    return { ok: true, slot: { kind: "literal", value: raw.value as Value } };
  }
  if (raw.kind === "formula") {
    if (!("ast" in raw)) {
      return { ok: false, message: `${objectName}.${key} (formula) is missing its ast` };
    }
    return { ok: true, slot: { kind: "formula", ast: raw.ast as FormulaAst, value: "value" in raw ? (raw.value as Value) : null } };
  }
  if (raw.kind === "derived") {
    return { ok: true, slot: { kind: "derived", value: null } };
  }
  return { ok: false, message: `${objectName}.${key} has an unrecognised slot kind ${JSON.stringify(raw.kind)}` };
}

/** A short, human-readable description of `typeof value`, for a top-level shape-error message — never itself throws. */
function describeTypeof(value: unknown): string {
  if (value === null) {
    return "null";
  }
  if (Array.isArray(value)) {
    return "an array";
  }
  return `a ${typeof value}`;
}
