const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_EXECUTABLE });
  const page = await browser.newPage({ viewport: { width: 1360, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.WORKSPACE_URL || 'http://127.0.0.1:5173/');
  await page.locator('#command-status').filter({ hasText: 'Ready' }).waitFor();
  assert.equal(await page.locator('.brand-mark').evaluate(mark => mark.tagName), 'svg');
  assert.ok(await page.locator('.brand-mark path').count() >= 3);
  assert.equal(await page.locator('#stage').evaluate(stage => getComputedStyle(stage).backgroundColor), 'rgb(244, 240, 229)');
  await page.screenshot({ path: 'dist/workspace-empty.png' });
  await page.locator('[data-command="circle"]').click();
  assert.equal(await page.locator('#welcome').isVisible(), false);
  assert.match(await page.locator('#command-status').textContent(), /center/);
  const canvas = await page.locator('#canvas').boundingBox();
  await page.mouse.click(canvas.x + 250, canvas.y + 220);
  await page.mouse.click(canvas.x + 310, canvas.y + 220);
  assert.equal(await page.locator('.object-item').count(), 1);
  const command = page.locator('#command');
  const run = async line => { await command.fill(line); await command.press('Enter'); };
  await run('table x=400 y=150 rows=3 cols=2');
  await run('set table_1.A1 = circle_1.radius * 2');
  await run('set circle_1.radius 80');
  await page.locator('.object-item').filter({ hasText: 'table_1' }).click();
  await run('props table_1');
  const downloadEvent = page.waitForEvent('download');
  await page.locator('[data-command="save"]').click();
  const download = await downloadEvent;
  const saved = JSON.parse(require('node:fs').readFileSync(await download.path(), 'utf8'));
  const table = saved.objects.find(object => object.name === 'table_1');
  assert.equal(Object.values(table.slots).find(slot => slot.kind === 'formula').value, 160);
  await command.press('ArrowUp');
  assert.equal(await command.inputValue(), 'props table_1');
  await command.press('ArrowDown');
  assert.equal(await command.inputValue(), '');
  await page.locator('#object-search').fill('circle');
  assert.equal(await page.locator('.object-item').count(), 1);
  await page.locator('#object-search').fill('');
  await page.locator('[data-command="fit"]').click();
  await page.locator('#history-toggle').click();
  assert.equal(await page.locator('#log').isVisible(), true);
  // A shut panel measures zero, so the scroll that follows each command lands
  // nowhere. The newest lines are what an operator opens the panel to read.
  assert.ok(await page.locator('#log').evaluate(log => log.scrollHeight > log.clientHeight && log.scrollTop + log.clientHeight >= log.scrollHeight - 2));
  await page.locator('#history-toggle').click();
  await page.locator('#help-toggle').click();
  assert.equal(await page.locator('#help-panel').isVisible(), true);
  await page.locator('#help-close').click();
  await page.screenshot({ path: 'dist/workspace-populated.png' });
  const sidebar = page.locator('#sidebar');
  const fullWidth = (await sidebar.boundingBox()).width;
  await page.locator('[data-sidebar-mode="compact"]').click();
  assert.ok((await sidebar.boundingBox()).width < fullWidth);
  const tools = await page.locator('.tool-grid button').evaluateAll(buttons => buttons.map(button => button.getBoundingClientRect().x));
  assert.equal(new Set(tools).size, 1);
  const grip = page.locator('#sidebar-resize');
  await grip.focus();
  await grip.press('ArrowRight');
  assert.equal((await sidebar.boundingBox()).width, 150);
  const handle = await grip.boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + 100);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 + 40, handle.y + 100);
  await page.mouse.up();
  assert.ok((await sidebar.boundingBox()).width >= 189);
  await page.screenshot({ path: 'dist/workspace-compact.png' });
  const beforeHide = (await page.locator('#stage').boundingBox()).width;
  await page.locator('[data-sidebar-mode="hidden"]').click();
  assert.equal(await sidebar.isVisible(), false);
  assert.ok((await page.locator('#stage').boundingBox()).width > beforeHide);
  await page.screenshot({ path: 'dist/workspace-hidden.png' });
  await page.locator('#sidebar-show').click();
  assert.equal(await sidebar.getAttribute('data-mode'), 'compact');
  await page.locator('[data-sidebar-mode="full"]').click();
  assert.equal((await sidebar.boundingBox()).width, fullWidth);
  await page.locator('.tool-grid [data-command="rect"]').click();
  await page.locator('#cancel-command').click();
  assert.equal(await page.locator('#cancel-command').isVisible(), false);
  await run('zoom 0.4');
  // A zoom reached by repeated steps is a float of full precision, and the dock
  // keeps the newest line on screen for as long as it is the newest.
  assert.match(await page.locator('#command-status').textContent(), /^zoom is now \d+(\.\d{1,4})?$/);
  await page.locator('[data-command="polygon"]').click();
  await run('5');
  const stage = await page.locator('#canvas').boundingBox();
  await page.mouse.click(stage.x + 450, stage.y + 370);
  await page.mouse.move(stage.x + 580, stage.y + 450);
  await page.screenshot({ path: 'dist/polygon-preview.png' });
  assert.equal(await page.locator('.object-item').count(), 2);
  await page.mouse.click(stage.x + 580, stage.y + 450);
  assert.equal(await page.locator('.object-item').count(), 3);
  await run('select polygon_1');
  await run('set polygon_1.radius = circle_1.radius * 2');
  const radiusRow = page.locator('.panel-row[data-path="radius"]');
  assert.equal(await radiusRow.getAttribute('data-kind'), 'formula');
  await radiusRow.getByRole('button', { name: 'Edit formula for radius', exact: true }).click();
  const formulaInput = radiusRow.locator('input');
  assert.equal(await formulaInput.inputValue(), '=circle_1.radius * 2');
  await formulaInput.fill('=circle_1.radius * 3');
  await formulaInput.press('Enter');
  assert.match(await radiusRow.textContent(), /240/);
  assert.equal(await page.locator('.panel-row[data-path="style.fillColor"] .panel-clip').textContent(), 'Unset');
  await page.screenshot({ path: 'dist/property-states.png' });
  await radiusRow.getByRole('button', { name: 'Unlink radius and keep its current value', exact: true }).click();
  assert.equal(await radiusRow.getAttribute('data-kind'), 'literal');
  assert.match(await radiusRow.textContent(), /240/);
  await radiusRow.getByRole('button', { name: 'Edit value for radius', exact: true }).focus();
  await page.keyboard.press('Enter');
  await radiusRow.locator('input').fill('100');
  await radiusRow.locator('input').press('Enter');
  assert.match(await radiusRow.textContent(), /100/);
  await run('math x=300 y=250 "x=4+4"');
  await run('select math_1');
  const sourceButton = page.locator('.panel-row[data-path="source"] .panel-clip');
  await sourceButton.click();
  const mathField = page.locator('math-field');
  await mathField.waitFor();
  assert.equal(await mathField.evaluate(field => field.mathVirtualKeyboardPolicy), 'manual');
  assert.equal(await page.evaluate(() => window.mathVirtualKeyboard.visible), false);
  await page.locator('#math-keyboard-toggle').click();
  assert.equal(await page.evaluate(() => window.mathVirtualKeyboard.visible), true);
  assert.equal(await page.locator('#math-keyboard-toggle').textContent(), 'Hide keyboard');
  await page.locator('#math-keyboard-toggle').click();
  assert.equal(await page.evaluate(() => window.mathVirtualKeyboard.visible), false);
  await page.locator('#math-keyboard-toggle').click();
  await mathField.press('Escape');
  assert.equal(await page.evaluate(() => window.mathVirtualKeyboard.visible), false);
  await sourceButton.click();
  await page.locator('#math-keyboard-toggle').click();
  await mathField.press('Enter');
  assert.equal(await page.evaluate(() => window.mathVirtualKeyboard.visible), false);
  const displaySelect = page.locator('.panel-row[data-path="display"] select');
  await displaySelect.selectOption({ label: 'Formula + result' });
  assert.ok(await displaySelect.evaluate(select => parseFloat(getComputedStyle(select).paddingRight) >= 24));
  await page.screenshot({ path: 'dist/math-controls.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'dist/workspace-mobile.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('[data-sidebar-mode="compact"]').click();
  await grip.focus();
  await grip.press('Home');
  assert.equal((await sidebar.boundingBox()).width, 120);
  await page.screenshot({ path: 'dist/workspace-mobile-compact.png' });
  await page.locator('[data-sidebar-mode="hidden"]').click();
  await page.locator('#sidebar-show').click();
  assert.equal(await sidebar.isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  console.log('Workspace checks passed: shape previews, formula editing and unlinking, keyboard property edits, creation, live formulas, selection, search, history, guide, cancellation, responsive layout. No browser errors.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
